# config.yaml for Movie Recommender ModelTrainer
# Specify directories and data sources for training

data:
  user_movie_interactions: "data/processed_data/user_movie_interactions.npz"
  pre_processed_movies: "data/processed_data/pre_processed_movies.csv"
  pre_processed_users: "data/processed_data/pre_processed_users.csv"

trainer:
  # Choose which data to use for training each model
  als_data: "user_movie_interactions"  # options: user_movie_interactions, pre_processed_movies, pre_processed_users
  user_user_data: "user_movie_interactions"
  item_item_data: "pre_processed_movies"

output:
  model_cache_dir: "models/models/"
  logs_dir: "preprocessing/"
